### ISSUE TITLE
Dire Maul - Lasher loot broken

### ISSUE THREAD

**Issue by Zylph** [elysium-project/classic-bug-tracker#869]
The Lasher's inside of Dire Maul seem to have had their loot tables recently broken.  This has happened before and was eventually fixed. Please look into this as currently the drop rates are non blizz-like.

**Comment by europoor** [comment]
I can confirm that this is indeed true, but I would like to add that the herb spawns are broken as well. I've only been getting 1 herb spawn per reset.

**Comment by nicholasmz0r** [comment]
I can confirm this. This is not Blizz-like. Please fix. Thank you

**Comment by Zellus902** [comment]
Drops have been a lot less lately, few and far between.

**Comment by Thenari** [comment]
I do remember when DM first came out the plants were changed from blizz like as the money influx coming from mages farming them was too much but that was a long time ago

**Comment by shenna-elysium** [comment]
Fixed. Wait for the server restart.

**Comment by Thenari** [comment]
Shenna please expand what do you mean by Fixed.

**Comment by Zylph** [comment]
The lashers are still not dropping loot like they are supposed to. Many times out of 5 packs, one or none have loot.

**Comment by Thenari** [comment]
Lol dude its been 1 day has a patch even happened yet :p plz remember we arent a big team like less than a handful of people who are smart and do Dev stuff

**Comment by JaronL13** [comment]
still a problem, no loot from them, only sometimes a green. 0 herbs

**Comment by Zylph** [comment]
Apologies for seeming inpatient. That was my misunderstanding.  I read the fix reply as it would go live at the next server reboot. We had one of those on Saturday. Thought that would cover it. Will wait for maintenance cycle.  Thank you for all your hard work and time you sink into this so we can be entertained.
<3

**Comment by Thenari** [comment]
Yeah shenna should of probs used to other label which ill add on now

**Comment by Zylph** [comment]
do we know when to expect the fix to be applied to live?

**Comment by Thenari** [comment]
It can be hard to tell. There are a lot of issues ahead of this in priority. Remember to take breaks from playing WoW its not like farming gold all day is your job :P

**Comment by Zylph** [comment]
I usually farm DM weekdays while at work since being a system admin has slow days if you're maintaining your systems correctly with enough preventative maintenance. It is better than staring at system stat dashboards.  Off to YouTube I go I guess :)

**Comment by Thenari** [comment]
https://forum.elysium-project.org/topic/29392-customization-of-content-gold-farmers/

Like i started playing on elysium when my bf wanted to try it.

But a quick google search. It looks like even older servers by elysium might of done this too

**Comment by Thenari** [comment]
It can be hard to tell how well combating gold sellers works but the elysium project decided they needed to do something... maybe we need a staff bot that appears when a single mage enters DM E and shows the mage a randomized scramble image of letters and numbers the player has to say correctly ;p

**Comment by Thenari** [comment]
Alrighty well nothing more needs to be done by me. Im unsubscribing and this thread will no longer be moderated.
